parameters:
#    msi_paint.example.class: Msi\Bundle\PaintBundle\Example

services:
    # Gallery
    msi_paint_gallery_admin:
        class: Msi\Bundle\PaintBundle\Admin\GalleryAdmin
        arguments: [ @msi_paint.gallery_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }
        calls:
            - [ setChild, [ @msi_paint_artwork_admin ] ]

    msi_paint.gallery_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Msi\Bundle\PaintBundle\Entity\Gallery ]
        parent: msi_cmf.manager

    # Artwork
    msi_paint_artwork_admin:
        class: Msi\Bundle\PaintBundle\Admin\ArtworkAdmin
        arguments: [ @msi_paint.artwork_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }
        calls:
            - [ setParent, [ @msi_paint_gallery_admin ] ]

    msi_paint.artwork_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Msi\Bundle\PaintBundle\Entity\Artwork ]
        parent: msi_cmf.manager
